version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      - env/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-database}
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./
      dockerfile: Dockerfile-backend
    restart: always
    container_name: backend
    depends_on:
      - postgres
      - redis
    env_file:
      - env/.env
    environment:
      DB_HOST: ${DB_HOST:-postgres}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-database}
      DB_USER: ${DB_USER:-user}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      MONGODB_NAME: ${MONGODB_NAME:-schedules}
      MONGODB_CLUSTER: ${MONGODB_CLUSTER:-mongo}
    ports:
      - "8080:8080"

  frontend:
    depends_on:
      - backend
    build: 
      context: ./
      dockerfile: Dockerfile-frontend
    ports:
      - "3000:3000"

  mongo:
    image: mongo:8
    container_name: mongo
    ports:
      - "27017:27017"
  
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
