version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
#    volumes:
 #     - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: source/
    restart: always
    container_name: backend
    depends_on:
      - postgres
      - redis
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: database
      DB_USER: user
      DB_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MONGODB_NAME: schedules
      MONGODB_CLUSTER: mongo
    ports:
      - "8080:8080"
#    volumes:
#      - "./backup:/backup"

  frontend:
    depends_on:
      - backend
    build: source/frontend/
    ports:
      - "3000:3000"
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
#    volumes:
#      - redis_data:/data
  
#volumes:
#  postgres_data:
#  redis_data:

