# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Use the Ubuntu 20.04 (Focal Fossa) base box
  config.vm.box = "ubuntu/focal64"

  # Global VirtualBox settings for all VMs
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"   # Assign 512MB of RAM
    vb.cpus = 1         # Allocate 1 CPU
  end

  # Mount the host 'source' directory inside guest
  config.vm.synced_folder "./source", "/vagrant/source"

  # Provision using external shell script
  config.vm.provision "shell" do |s|
    s.path = "./scripts/provision-script.sh"
  end
end
